buildDeps:
  - node-0.12.7
  - hs-build-tools
  - jdk8
  - maven3

steps:
  - name: build
    description: "mvn clean generate-resources"
    commands:
      - 'echo "build"'
      - mvn clean generate-resources
  - name: publish
    description: "bender-deps cdn-publish"
    activeByDefault: false
    commands:
      - 'echo "npm install"'
      - node/node node/npm/cli.js --globalconfig /usr/share/hubspot/jenkins-home/.npmrc install bender-deps
      - 'echo "cdn-publish"'
      - node/node ./node_modules/.bin/bender-deps cdn-publish SingularityUI-$GIT_BRANCH@1.$MODULE_BUILD_NUMBER dist/static
  - name: notify
    description: "publish-build-success"
    activeByDefault: false
    commands:
      - 'echo "notify"'
      - command: publish-build-success --project $BLAZAR_COORDINATES --build-num $MODULE_BUILD_NUMBER

stepActivation:
  publish:
    branches: [hs_staging, hs_qa, hs_stable, blazar2]
  notify:
    branches: [hs_staging, hs_qa, hs_stable, blazar2]
